[package]
name = "bytelink"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
insta = { version = "1.43.2", features = ["json"] }
jiff = { version = "0.2.15", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
